### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by swiftg** [pulibrary/Scribe#6]
Add rotation button to image viewer.  Zena has this implemented on dev.

**Comment by kevinreiss** [comment]
@swiftg Zena was working on her personal machine. @sdellis isn't this just a feature that can be turned in the Openseadragon configuration?

**Comment by sdellis** [comment]
[These lines](https://github.com/pulibrary/Scribe/blob/osd-rotation/scripto/index/transcribe.php#L297-L302) are what adds rotation.  Not closing it out yet because still untested.

**Comment by sdellis** [comment]
Done.
