### ISSUE TITLE
Transcription Labels

### ISSUE THREAD

**Issue by swiftg** [pulibrary/Scribe#7]
Change labels found here: http://transcribe.princeton.edu/collections/show/1
Changes: 
"started" to "transcribed."  Example: "2% started" becomes "2% transcribed."
"Needs Review" to "100% transcribed"

Next level labels (found here, http://transcribe.princeton.edu/items/show/20) are fine as is.

**Comment by kevinreiss** [comment]
Okay, these should be simple changes.
