### ISSUE TITLE
Import New Collections

### ISSUE THREAD

**Issue by swiftg** [pulibrary/Scribe#8]
Thomas Adams Papers (Finding Aids): http://findingaids.princeton.edu/collections/C1452
Cogswell, Diary of an Officer: https://pulsearch.princeton.edu/catalog/8870341

**Comment by kevinreiss** [comment]
@swiftg is the latter still being digitized?

**Comment by swiftg** [comment]
@kevinreiss Waiting for image METS: https://trello.com/c/Ie1mAfde

**Comment by kevinreiss** [comment]
@swiftg For http://findingaids.princeton.edu/collections/C1452 it seems components 1-5 all have content. Should each be loaded as a separate listing in the site?

**Comment by kevinreiss** [comment]
Regarding the Trello link, is that something you are waiting on from us or is that something Roel needs to do?

**Comment by kevinreiss** [comment]
@sdellis Could you load volumes 1 and 2 from C!452 when you get a chance? We have a good backup of the database just in case something were to go really off the rails.

**Comment by sdellis** [comment]
These are done:
http://transcribe.princeton.edu/items/show/32
http://transcribe.princeton.edu/items/show/33
